### ISSUE TITLE
MD Standard files: Types

### ISSUE THREAD

**Issue by firasm** [open-resources/scripts#10]
I suggest the "type" field in the header files of our `md` files be changed to match the [prairie-learn question types](https://prairielearn.readthedocs.io/en/latest/elements/).

## Useful question types

Here is the list of questions that would be useful for us:

- [x] 1. pl-multiple-choice: Selecting only one option from a list.
- [x] 2. pl-number-input: Fill in a numerical value within a specific tolerance level such as 3.14, -1.921, and so on.
- [x] 3. pl-dropdown: Select an answer from answers in a drop-down box.
- [x] 4. pl-checkbox: Selecting multiple options from a list.
- [ ] 5. pl-drawing: Graph/plot questions.
- [x] 6. pl-symbolic-input: Fill in a symbolic value such as x^2, sin(z), mc^2, and so on.
- [ ] 7. pl-string-input: Fill in a string value such as "Illinois", "GATTACA", "computer", and so on.
- [ ] 8. pl-overlay: labeling figures.
- [x] 9. pl-integer-input: Fill in an integer value such as -71, 0, 5, 21, and so on.
- [x] 10. multi-part: a question with more than one parts.

I'm going to start creating the questions above.

- [ ] ~~6. pl-order-blocks: Select and arrange given blocks of code or text.~~
    - This one is super difficult to code, will have to think about whether it's worth doing.

## Other question types

- pl-matrix-component-input: Fill in a matrix using grid that has an input area for each element.
- pl-matrix-input: Supply a matrix in a supported programming language format.
- pl-file-editor: Provide an in-browser code editor for writing and submitting code.
- pl-file-upload: Provide a submission area to obtain a file with a specific naming scheme.
- pl-threejs: Enables 3D scene display and problem submission.

**Comment by firasm** [comment]
Hey @michaelwkudla just wanted to give you a heads up that I'm creating these problem types and putting them here: https://github.com/open-resources/scripts/tree/main/md_file_standards

Let me know if you also want to help and we can distribute a couple. Though, I think it might be better for you to [tackle this issue here about graphing on PL.](https://github.com/open-resources/instructor_physics_bank/issues/3)

**Comment by michaelwkudla** [comment]
Working on no. 5.

**Comment by michaelwkudla** [comment]
Ok, symbolic is largely sorted out. What's the next priority? String and then figures?

**Comment by firasm** [comment]
Great! There's a new question type [coming soon](https://github.com/PrairieLearn/PrairieLearn/issues/4030) for "Essay" questions. I think that'll be better for us than String. Unfortunately it's not available yet so let's kick this can down the road a bit.

I'll let you check box 6 above :-)

As far as next priority, I have assigned @gbovett to [this question](https://github.com/open-resources/instructor_physics_bank/issues/10) which would be an AWESOME question to randomize. 

In parallel, can you work on [this one](https://github.com/open-resources/instructor_physics_bank/issues/3) ?

**Comment by firasm** [comment]
Latest md files have been merged in using #22. I am going to close this for now, will come back later to drawing, string, and overlay q types.
