### ISSUE TITLE
MD Question Version Control

### ISSUE THREAD

**Issue by michaelwkudla** [open-resources/scripts#11]
We will need to have some methodology of keeping track of which "version" of MD file template was used to create a given question. 

One way to do this would be: 
MD example files have a "version" associated with them. We could start with version 0.1 for now. 
When a new version of an example file is pulled into the database, the old one will be deprecated of course, but we still need the script to be able to read the old version. 

So, with each new md file version, there may need to be a change to the conversion script associated, or a new function to be called for the specific version. This way, whichever version of md file format is used to create a question, the md2pl script can use the correct conversion script.

Perhaps this can be a topic for our scripts meeting this week.

**Comment by firasm** [comment]
agreed, good suggestion.

Let's add a tag in the YAML header called: `template_version`.

So the header files would look like:

```
---
title: Distance travelled
type: multiple-choice
template_version: 0.1
author: Firas Moosvi
source: original
tags:
- kinematics
```

**Comment by michaelwkudla** [comment]
@gbovett Are you including the "template version" in your conversion scripts so that we know which version the converter was meant for? Can we consider this closed?

**Comment by firasm** [comment]
We can close this, the plan is to add some unit tests to the converter script to make sure things don't diverge.
