### ISSUE TITLE
Symbolic Interpretation Issue

### ISSUE THREAD

**Issue by michaelwkudla** [open-resources/scripts#12]
Working on this demo question: 
https://ca.prairielearn.org/pl/course_instance/2300/instructor/question/188273/file_view

Based on this documentation: 
https://prairielearn.readthedocs.io/en/latest/elements/#pl-symbolic-input-element

Based on the documentation, the question should work, but it crashes. Haven't sorted out why yet. 
Happy to have others take a look as well.

**Comment by firasm** [comment]
Fixed:

it was

```
data['correct_answers']['symbolic_math'] = pl.to_json(F)
```

(not `correct_answer`) - I think the docs are wrong and probably need to be updated.

**Comment by michaelwkudla** [comment]
Thanks Firas.
