### ISSUE TITLE
Test some other projects for converting/executing perl

### ISSUE THREAD

**Issue by cbm755** [open-resources/scripts#14]
Re #8.  The following looks promising to conservatively auto-translate Perl code to Python:

https://github.com/softpano/pythonizer

  * I can't find a license, so one would need to contact the author.

I also saw https://metacpan.org/pod/release/GAAS/pyperl-1.0/perlmodule.pod and various similar things that allow executing Perl code within Python.

**Comment by firasm** [comment]
[Opened an issue in pythonizer](https://github.com/softpano/pythonizer/issues/5) to request a license. 

Thanks!

**Comment by firasm** [comment]
[License now added](https://github.com/softpano/pythonizer/blob/master/license.html).
