### ISSUE TITLE
Webwork Script - Optimize Speed

### ISSUE THREAD

**Issue by Parsa-Rajabi** [open-resources/scripts#28]
Investigate the root cause of script running slow and brainstorm solutions

**Comment by Parsa-Rajabi** [comment]
Looking into this is while completing #29

**Comment by Parsa-Rajabi** [comment]
Completed via https://github.com/open-resources/scripts/commit/1dcf28780fed9cfad5217e840fb779c1c68e5aaf

**Comment by firasm** [comment]
Nice work!!!
