### ISSUE TITLE
Webwork Script - Modularization  

### ISSUE THREAD

**Issue by Parsa-Rajabi** [open-resources/scripts#29]
Break script into sections and add functions to handle different aspects. Firas suggested to use python dics to pass around values between functions

**Comment by firasm** [comment]
Consider using *args and **kwargs for wrapper functions.

**Comment by Parsa-Rajabi** [comment]
Completed initial function to split file into bite-size pieces, more to follow

**Comment by Parsa-Rajabi** [comment]
functions created thus far:

1. split file into bite-size pieces
2. metadata extraction
3. image extraction
4. determine problem type (checkbox/numerical/string etc.)
5. yaml dump

functions TODO:
1. problem extraction (including multi-parts)
2. answer extraction 
3. sanity tests

**Comment by Parsa-Rajabi** [comment]
problem extraction is still in progress:
- A new way of extracting problem text: https://github.com/open-resources/scripts/commit/2f794743f6f919f080e1eeca4589130037bc8c54
- Took a more optimized approach to handle questions w/ and w/o images: https://github.com/open-resources/scripts/commit/bc727c2e8c403c119bc9dfe94dee7cd97d547cd5
- Fixed a bug with hint not being removed https://github.com/open-resources/scripts/commit/00a06fd406c72f4bddcdee6f88afd8f15d93041e 
-

**Comment by Parsa-Rajabi** [comment]
problem extraction has been completed.
- extracted parts from file
- added question type for each part to metadata

last item left:
- add answer to server section

**Comment by Parsa-Rajabi** [comment]
All complete!
