### ISSUE TITLE
Webwork Script - Modify output for PL script

### ISSUE THREAD

**Issue by Parsa-Rajabi** [open-resources/scripts#42]
There are currently some errors when PL script is ran on the `.md` files:

```
There is an error in this problem:
	- File path: source_ww/output_md/College_Physics_Urone/5.Friction_Drag_and_Elasticity/5-01.Friction/NU_U17_05_01_002.md
	- Error: string indices must be integers
source_ww/output_md/College_Physics_Urone/5.Friction_Drag_and_Elasticity/5-01.Friction/NU_U17_05_01_006.md
Check the heading levels, is there one that doesn't belong? Or is the heading level incorrect? For e.g., it should be ### Answer Section (this is not necessarily where the issue is).
There is an error in this problem:
	- File path: source_ww/output_md/College_Physics_Urone/5.Friction_Drag_and_Elasticity/5-01.Friction/NU_U17_05_01_006.md
	- Error: list index out of range
source_ww/output_md/College_Physics_Urone/5.Friction_Drag_and_Elasticity/5-01.Friction/NU_U17_05_01_016.md
Check the heading levels, is there one that doesn't belong? Or is the heading level incorrect? For e.g., it should be ### Answer Section (this is not necessarily where the issue is).
```

Errors:
- string indices must be integers
- list index out of range

Look into the root cause of the errors and resolve them

**Comment by firasm** [comment]
I just did some quick hacking and I think I see the issue:

In the file `NU_U17-33-02-002.md`, the level two heading doesn't look formatted correctly:

```
# {{ params.vars.title }}## Part 1 
The ratio of the strong to the weak force and the ratio of the strong force to theelectromagnetic force become (1) under circumstances where they are unified. Whatare the ratios of the strong force to those two forces under normal circumstances? 
```

It should be:

```
# {{ params.vars.title }}

## Part 1 
The ratio of the strong to the weak force and the ratio of the strong force to theelectromagnetic force become (1) under circumstances where they are unified. Whatare the ratios of the strong force to those two forces under normal circumstances? 
```

**Comment by firasm** [comment]
Also in the same file I can see in Lines 39 and 40:

```
      # Randomize Variables
      $SE = 1/(10**-2);
      $SW = 1/(10**-13);
```
I think those `$` aren't valid python names

**Comment by firasm** [comment]
Ok I think the largest issue is the YAML export.

Remember that `|-` means that "everything after it should be interpreted as a multi-line string" so we only want that for things like `imports` and `generate`.

If we do it for `server`, it will not parse the sub-levels as separate dictionary keys:
<img width="547" alt="Screen Shot 2021-09-23 at 7 42 59 AM" src="https://user-images.githubusercontent.com/2507459/134529041-5b83a6cb-e574-47f8-a11e-08950eb76bdf.png">

So we need to get rid of `|-` in server

**Comment by firasm** [comment]
`TBD` needs to be commented out as anything in generate will get run

<img width="724" alt="Screen Shot 2021-09-23 at 7 49 50 AM" src="https://user-images.githubusercontent.com/2507459/134530092-4c092468-d906-4a18-a030-6428847153f1.png">

**Comment by firasm** [comment]
One other oddity: it looks like the YAML section starts with `part2` rather than `part1`

<img width="266" alt="Screen Shot 2021-09-23 at 8 08 02 AM" src="https://user-images.githubusercontent.com/2507459/134533483-d575ed0d-2f80-4cff-8de7-51dfaf2c076e.png">

**Comment by firasm** [comment]
For the problem type, `type: Numerical` should be: `type: number-input`

**Comment by firasm** [comment]
After I fix those relatively minor issues, IT WORKS!!!

<img width="373" alt="Screen Shot 2021-09-23 at 8 11 56 AM" src="https://user-images.githubusercontent.com/2507459/134534280-e808982f-3f28-48d4-b9e8-53adf6cb1ba6.png">

I'm so excited! 🎉

**Comment by firasm** [comment]
P.S. I've logged all the changes I had to make to the md file [in this commit](https://github.com/open-resources/instructor_physics_bank/commit/125439059e93bcfb750b2ad20e1e4bbb093f68f3)

**Comment by Parsa-Rajabi** [comment]
> For the problem type, type: Numerical should be: type: number-input

Fixed

**Comment by Parsa-Rajabi** [comment]
> Also in the same file I can see in Lines 39 and 40:
> 
> ```
>       # Randomize Variables
>       $SE = 1/(10**-2);
>       $SW = 1/(10**-13);
> ```
> 
> I think those `$` aren't valid python names
> 
> We also probably should replace all `**` to `E`
> 
> <img alt="Screen Shot 2021-09-23 at 7 25 47 AM" width="190" src="https://user-images.githubusercontent.com/2507459/134525594-61fbfe09-8e39-4a27-b651-36c31dba109c.png">

Fixed. Removed $ and replaced `**` with `E`

**Comment by Parsa-Rajabi** [comment]
> `TBD` needs to be commented out as anything in generate will get run
> 
> <img alt="Screen Shot 2021-09-23 at 7 49 50 AM" width="724" src="https://user-images.githubusercontent.com/2507459/134530092-4c092468-d906-4a18-a030-6428847153f1.png">

already completed

**Comment by Parsa-Rajabi** [comment]
> Ok I think the largest issue is the YAML export.
> 
> Remember that `|-` means that "everything after it should be interpreted as a multi-line string" so we only want that for things like `imports` and `generate`.
> 
> If we do it for `server`, it will not parse the sub-levels as separate dictionary keys:
> <img alt="Screen Shot 2021-09-23 at 7 42 59 AM" width="547" src="https://user-images.githubusercontent.com/2507459/134529041-5b83a6cb-e574-47f8-a11e-08950eb76bdf.png">

Addressed all server items except `generate`:
https://github.com/open-resources/scripts/commit/81a4c31b883eea2ce48bed79106a038415db6abf

- Still need to identify how and why `generate` does not output results as intended.

**Comment by Parsa-Rajabi** [comment]
# Part Subsections
>So we need to get rid of `|-` in server and in the parts:
> <img width="371" alt="Screen Shot 2021-09-23 at 7 53 04 AM" src="https://user-images.githubusercontent.com/2507459/134530688-7dfde084-c98c-46e6-a0ab-7bbd03af3231.png">

> One other oddity: it looks like the YAML section starts with `part2` rather than `part1`
> <img alt="Screen Shot 2021-09-23 at 8 08 02 AM" width="266" src="https://user-images.githubusercontent.com/2507459/134533483-d575ed0d-2f80-4cff-8de7-51dfaf2c076e.png">

- Still need to identify the root cause of part#s and ensure `|-` is removed from them

**Comment by Parsa-Rajabi** [comment]
All items are complete now! 

Latest changes include:
- Each question has its own folder 
- All question images are being copied to the question folder for PL
- Part # issue has been fixed
