### ISSUE TITLE
Content from Webwork on GitHub

### ISSUE THREAD

**Issue by firasm** [open-resources/scripts#6]
I had a meeting with Agnes D'Entremont and Jennifer Kirkey from UBC-V and Douglas College and they have put together a LOT of physics problems.

Here is the email in full, along with the links:

> Okay, here’s the content dump.  Feel free to ask about any of this. 
> 
> What we’ve done: 
> Our 2nd year engineering problems (multiple topics): https://github.com/ubc-mech2/UBC-engineering-webwork
> (Note that “tested” means deployed in a class. Need to deploy before submission to OPL. All problems tested by development team).  
> 
> Our 1st and 2nd year mechanics problems (working directory): https://github.com/ubc-mech2/OER-mechanics-webwork
> 
> 2nd year biomechanics: https://github.com/ubc-mech2/OER-biomechanics-webwork
> 
> In the above repos, any images without a CC license shouldn’t be used. 
> 
> 
> What others have done:
> OpenStax Physics: https://github.com/openwebwork/webwork-open-problem-library/tree/master/Contrib/BrockPhysics
> 
> Statics: https://github.com/openwebwork/webwork-open-problem-library/tree/master/Contrib/WhatcomCC
> 
> Statics, Thermo, Solid Mech: https://github.com/openwebwork/webwork-open-problem-library/tree/master/Contrib/LaTech
> 
> Fluids: https://github.com/openwebwork/webwork-open-problem-library/tree/master/Contrib/QueensU
> 
> EE: https://github.com/openwebwork/webwork-open-problem-library/tree/master/Contrib/NCSU
> 
> Cheers,
> Agnes
>

**Comment by firasm** [comment]
Reminder @Parsa-Rajabi : 

We also want to pull the WW problems from here:

> Our 1st and 2nd year mechanics problems (working directory): https://github.com/ubc-mech2/OER-mechanics-webwork

**Comment by firasm** [comment]
@Parsa-Rajabi see above ^

**Comment by firasm** [comment]
hey @Parsa-Rajabi - should this issue be closed ?

There is also another set of questions here:  https://github.com/ubc-mech2/OER-mechanics-webwork

**Comment by Parsa-Rajabi** [comment]
Let's close this issue and use this: https://github.com/open-resources/scripts/issues/32 for UBC Mech
