### ISSUE TITLE
Moving `correct_answer` key/value pair from data['params'] to data['vars']

### ISSUE THREAD

**Issue by firasm** [open-resources/scripts#9]
What would be the consequence (if any) to the md_to_pl script if the `correct_answer` was moved from data['params'] to data['vars']?

**Comment by firasm** [comment]
This is not advisable based on the PL docs.

**Comment by gbovett** [comment]
I have been using data['params'] for all non answer fields and data['correct_answers'] for possible answers. I have local version of the md sample file that I modify as needed as im developing the conversion script; I was going to wait for our next meeting before overwriting the github file but can post it if you would like

**Comment by firasm** [comment]
Perfect, that's good - that's what the docs recommend/require. 

I am actively updating the [template files](https://github.com/open-resources/scripts/blob/main/md_file_standards/q01_multiple-choice/q01_multiple-choice.md) at the moment.

I've done several cleanup things:

- Since we will now **always** have a part1, it makes sense that `data['correct_answers']` should be `data['correct_answers']['part1']` 
- The above changes makes the "answer" key:value in the `part1` YAML header redundant so I've removed that
- Let's leave the `choices: ans1, ans2, ans3, ans4 ` key:value in for now,

**Comment by firasm** [comment]
A version of this has been implemented in PR #17. This will come to bite us in the butt though, so let this be some foresight...
